In [6]:
import pandas as pd
import numpy as np
from scipy.stats import stats

In [7]:
data=pd.read_excel('C:\\Users\\DELL\\Desktop\\ATI\\python\\proj_data.xlsx')

In [8]:
data.columns

Index(['Sl no', 'Gender', 'Designation', 'Training', 'Des_Grp', 'Age', 'TD1',
       'TD2', 'TD3', 'TD4', 'TD5', 'TD6', 'TD7', 'TD8', 'Training_Delivery',
       'TT1', 'TT2', 'TT3', 'TT4', 'TT5', 'TT6', 'Training_Transfer', 'EM1',
       'EM2', 'EM3', 'Employee_Motivation', 'EP1', 'EP2', 'EP3', 'EP4', 'EP5',
       'Emploee_Performance'],
      dtype='object')

In [10]:
#Chi square test of independence is used for hypothesis testing since 
#there are categoric variables only(categoric variables have only frequency/count/mode)

from scipy import stats
#Hypothesis 1: 
#Ho:Training delivery has no significant impact on employeeperformance.
#Ha: Training delivery hassignificant impact on employee performance.
crosstab1 = pd.crosstab(data['Training_Delivery'], data['Emploee_Performance'])
crosstab1
stats.chi2_contingency(crosstab1)

(1043.678853815958,
 4.098800725213339e-147,
 120,
 array([[ 0.0989011 ,  0.0989011 ,  0.23076923,  0.69230769,  2.04395604,
          0.72527473,  0.79120879,  1.02197802,  2.07692308,  0.1978022 ,
          1.02197802],
        [ 0.45054945,  0.45054945,  1.05128205,  3.15384615,  9.31135531,
          3.3040293 ,  3.6043956 ,  4.65567766,  9.46153846,  0.9010989 ,
          4.65567766],
        [ 0.03296703,  0.03296703,  0.07692308,  0.23076923,  0.68131868,
          0.24175824,  0.26373626,  0.34065934,  0.69230769,  0.06593407,
          0.34065934],
        [ 0.17582418,  0.17582418,  0.41025641,  1.23076923,  3.63369963,
          1.28937729,  1.40659341,  1.81684982,  3.69230769,  0.35164835,
          1.81684982],
        [ 0.48351648,  0.48351648,  1.12820513,  3.38461538,  9.99267399,
          3.54578755,  3.86813187,  4.996337  , 10.15384615,  0.96703297,
          4.996337  ],
        [ 0.93406593,  0.93406593,  2.17948718,  6.53846154, 19.3040293 ,
          6.84981685

In [11]:
#Hypothesis 2:
#Ho:Training transfer has no significant impact on employeeperformance.
#Ha: Training transfer has significant impact on employee performance.
crosstab2 = pd.crosstab(data['Training_Transfer'], data['Emploee_Performance'])
crosstab2
stats.chi2_contingency(crosstab2)

(1268.3821204459166,
 6.391696515666485e-191,
 120,
 array([[3.29670330e-02, 3.29670330e-02, 7.69230769e-02, 2.30769231e-01,
         6.81318681e-01, 2.41758242e-01, 2.63736264e-01, 3.40659341e-01,
         6.92307692e-01, 6.59340659e-02, 3.40659341e-01],
        [1.53846154e-01, 1.53846154e-01, 3.58974359e-01, 1.07692308e+00,
         3.17948718e+00, 1.12820513e+00, 1.23076923e+00, 1.58974359e+00,
         3.23076923e+00, 3.07692308e-01, 1.58974359e+00],
        [2.74725275e-01, 2.74725275e-01, 6.41025641e-01, 1.92307692e+00,
         5.67765568e+00, 2.01465201e+00, 2.19780220e+00, 2.83882784e+00,
         5.76923077e+00, 5.49450549e-01, 2.83882784e+00],
        [2.96703297e-01, 2.96703297e-01, 6.92307692e-01, 2.07692308e+00,
         6.13186813e+00, 2.17582418e+00, 2.37362637e+00, 3.06593407e+00,
         6.23076923e+00, 5.93406593e-01, 3.06593407e+00],
        [6.70329670e-01, 6.70329670e-01, 1.56410256e+00, 4.69230769e+00,
         1.38534799e+01, 4.91575092e+00, 5.36263736e+00, 6.

In [12]:
#Hypothesis 3:
#Ho: Motivation has no significant impact on employee performance.
#Ha: Motivation has significant impact on employee performance.
crosstab3 = pd.crosstab(data['Employee_Motivation'], data['Emploee_Performance'])
crosstab3
stats.chi2_contingency(crosstab3)

(491.36575851490954,
 4.6570051726468763e-79,
 40,
 array([[ 0.32967033,  0.32967033,  0.76923077,  2.30769231,  6.81318681,
          2.41758242,  2.63736264,  3.40659341,  6.92307692,  0.65934066,
          3.40659341],
        [ 0.86813187,  0.86813187,  2.02564103,  6.07692308, 17.94139194,
          6.36630037,  6.94505495,  8.97069597, 18.23076923,  1.73626374,
          8.97069597],
        [ 0.71428571,  0.71428571,  1.66666667,  5.        , 14.76190476,
          5.23809524,  5.71428571,  7.38095238, 15.        ,  1.42857143,
          7.38095238],
        [ 0.40659341,  0.40659341,  0.94871795,  2.84615385,  8.4029304 ,
          2.98168498,  3.25274725,  4.2014652 ,  8.53846154,  0.81318681,
          4.2014652 ],
        [ 0.68131868,  0.68131868,  1.58974359,  4.76923077, 14.08058608,
          4.996337  ,  5.45054945,  7.04029304, 14.30769231,  1.36263736,
          7.04029304]]))

In [13]:
#Hypothesis 4:
#Ho:Training delivery has no significant impact on training transfer.
#Ha: Training delivery has significant impact on training transfer.
crosstab4 = pd.crosstab(data['Training_Delivery'], data['Training_Transfer'])
crosstab4
stats.chi2_contingency(crosstab4)

(1349.0949980415166,
 1.0621524324570075e-194,
 144,
 array([[9.89010989e-02, 4.61538462e-01, 8.24175824e-01, 8.90109890e-01,
         2.01098901e+00, 9.89010989e-02, 5.60439560e-01, 1.25274725e+00,
         7.25274725e-01, 1.97802198e-01, 1.31868132e+00, 3.29670330e-02,
         5.27472527e-01],
        [4.50549451e-01, 2.10256410e+00, 3.75457875e+00, 4.05494505e+00,
         9.16117216e+00, 4.50549451e-01, 2.55311355e+00, 5.70695971e+00,
         3.30402930e+00, 9.01098901e-01, 6.00732601e+00, 1.50183150e-01,
         2.40293040e+00],
        [3.29670330e-02, 1.53846154e-01, 2.74725275e-01, 2.96703297e-01,
         6.70329670e-01, 3.29670330e-02, 1.86813187e-01, 4.17582418e-01,
         2.41758242e-01, 6.59340659e-02, 4.39560440e-01, 1.09890110e-02,
         1.75824176e-01],
        [1.75824176e-01, 8.20512821e-01, 1.46520147e+00, 1.58241758e+00,
         3.57509158e+00, 1.75824176e-01, 9.96336996e-01, 2.22710623e+00,
         1.28937729e+00, 3.51648352e-01, 2.34432234e+00, 5.8608058

In [14]:
#Hypothesis 5:
#Ho:Training delivery has no significant impact on employee motivation.
#Ha: Training delivery has significant impact on employee motivation.
crosstab5 = pd.crosstab(data['Training_Delivery'], data['Employee_Motivation'])
crosstab5
stats.chi2_contingency(crosstab5)

(507.84576406739825,
 4.564473758466751e-78,
 48,
 array([[ 0.98901099,  2.6043956 ,  2.14285714,  1.21978022,  2.04395604],
        [ 4.50549451, 11.86446886,  9.76190476,  5.55677656,  9.31135531],
        [ 0.32967033,  0.86813187,  0.71428571,  0.40659341,  0.68131868],
        [ 1.75824176,  4.63003663,  3.80952381,  2.16849817,  3.63369963],
        [ 4.83516484, 12.73260073, 10.47619048,  5.96336996,  9.99267399],
        [ 9.34065934, 24.5970696 , 20.23809524, 11.52014652, 19.3040293 ],
        [ 1.75824176,  4.63003663,  3.80952381,  2.16849817,  3.63369963],
        [ 0.65934066,  1.73626374,  1.42857143,  0.81318681,  1.36263736],
        [ 0.43956044,  1.15750916,  0.95238095,  0.54212454,  0.90842491],
        [ 2.96703297,  7.81318681,  6.42857143,  3.65934066,  6.13186813],
        [ 0.32967033,  0.86813187,  0.71428571,  0.40659341,  0.68131868],
        [ 0.65934066,  1.73626374,  1.42857143,  0.81318681,  1.36263736],
        [ 1.42857143,  3.76190476,  3.0952381 ,  1

In [15]:
#Hypothesis 6:
#Ho:Employee motivation has no significant impact on training transfer.
#Ha:Employee motivation has significant impact on training transfer.
crosstab6 = pd.crosstab(data['Employee_Motivation'], data['Training_Transfer'])
crosstab6
stats.chi2_contingency(crosstab6)

(590.6009252917565,
 1.5534639672548478e-94,
 48,
 array([[ 0.32967033,  1.53846154,  2.74725275,  2.96703297,  6.7032967 ,
          0.32967033,  1.86813187,  4.17582418,  2.41758242,  0.65934066,
          4.3956044 ,  0.10989011,  1.75824176],
        [ 0.86813187,  4.05128205,  7.23443223,  7.81318681, 17.65201465,
          0.86813187,  4.91941392, 10.996337  ,  6.36630037,  1.73626374,
         11.57509158,  0.28937729,  4.63003663],
        [ 0.71428571,  3.33333333,  5.95238095,  6.42857143, 14.52380952,
          0.71428571,  4.04761905,  9.04761905,  5.23809524,  1.42857143,
          9.52380952,  0.23809524,  3.80952381],
        [ 0.40659341,  1.8974359 ,  3.38827839,  3.65934066,  8.26739927,
          0.40659341,  2.3040293 ,  5.15018315,  2.98168498,  0.81318681,
          5.42124542,  0.13553114,  2.16849817],
        [ 0.68131868,  3.17948718,  5.67765568,  6.13186813, 13.85347985,
          0.68131868,  3.86080586,  8.63003663,  4.996337  ,  1.36263736,
          9.08

Output:
The first value is the Chi-square value, followed by the p-value, then comes the degrees of freedom (3), and lastly it outputs the expected frequencies as an array. If all of the expected frequencies are greater than 5, the chi2 test results can be trusted. We can reject the null hypothesis if the p-value is less than 0.05

From the above test results all the p values are <0.05, thus the null hypotheses are rejected.
However, the results of the chi square tests cannot be trusted since the expected frequencies are not >5.